version: "3.7"
services:
  app:
    build:
      args:
        user: dean
        uid: 1001
      context: ./.docker
      dockerfile: Dockerfile
    image: library
    container_name: library-app
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - library

  db:
    image: mysql:5.7
    container_name: library-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'lara_db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'lara_password'
      MYSQL_USER: 'lara_user'
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - library

  nginx:
    image: nginx:1.17-alpine
    container_name: library-nginx
    restart: unless-stopped
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - library
